### ISSUE TITLE
Increase of upload limits

### ISSUE THREAD

**Issue by mkalz** [eummena/moodle-1click-app-digitalocean#1]
I have adapted the php.ini at /etc/php/7.3/fpm but changes do not take effect despite restarting apache. Any ideas?

**Comment by muhzak** [comment]
> I have adapted the php.ini at /etc/php/7.3/fpm but changes do not take effect despite restarting apache. Any ideas?

What are the chances, the one issue that's open that I need help with. I figured it out. 

So edit the file first by:

vi /etc/php/7.3/fpm/php.ini

then after adding at the end for example:

; Custom updates
upload_max_filesize = 128M
post_max_size = 128M

save & exit (press shift + colon - type x! and press enter) 

 and then run 

service php7.3-fpm restart 


This just worked for me.

**Comment by mkalz** [comment]
Thanks so much. Of course I forgot to restart PHP 🤷‍♂️.
